#!/usr/bin/env bash
set -euo pipefail

resolve_workspace_root() {
    local start_dir="${1:-$(pwd)}"
    local candidate="${start_dir}"
    while [[ "${candidate}" != "/" ]]; do
        if [[ -d "${candidate}/scripts" && -d "${candidate}/docs" && -d "${candidate}/examples" ]]; then
            printf '%s\n' "${candidate}"
            return 0
        fi
        candidate="$(dirname "${candidate}")"
    done
    local git_root=""
    git_root="$(git -C "${start_dir}" rev-parse --show-toplevel 2>/dev/null || true)"
    if [[ -n "${git_root}" && -d "${git_root}/FEM4C/scripts" && -d "${git_root}/FEM4C/docs" && -d "${git_root}/FEM4C/examples" ]]; then
        printf '%s\n' "${git_root}/FEM4C"
        return 0
    fi
    if [[ -n "${git_root}" && -d "${git_root}/scripts" && -d "${git_root}/docs" && -d "${git_root}/examples" ]]; then
        printf '%s\n' "${git_root}"
        return 0
    fi
    echo "FAIL: unable to resolve workspace root" >&2
    return 1
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(resolve_workspace_root "${SCRIPT_DIR}")"

if [[ $# -ne 4 ]]; then
    echo "Usage: bash tools/runners/mixed_bounded/run_mixed_macro_local_replay_split_generic_v1.sh <mixed_manifest.json|mixed_oneway_outdir> <mbd_deck> <fem_deck> <outdir>" >&2
    exit 2
fi

MIXED_INPUT="$1"
MBD_DECK="$2"
FEM_DECK="$3"
OUT_DIR="$4"

MIXED_ONEWAY_DIR="${OUT_DIR}/mixed_oneway"
REDUCED_DIR="${MIXED_ONEWAY_DIR}/reduced_feedback"
MBD_REPLAY_DIR="${OUT_DIR}/mbd_replay"
FEM_REPLAY_DIR="${OUT_DIR}/fem_replay"
HANDOFF_MANIFEST="${OUT_DIR}/split_replay_handoff_manifest.json"
SUMMARY_JSON="${OUT_DIR}/mixed_split_replay_summary.json"
SUMMARY_MD="${OUT_DIR}/mixed_split_replay_summary.md"

rm -rf "${OUT_DIR}"
mkdir -p "${OUT_DIR}" "${MBD_REPLAY_DIR}" "${FEM_REPLAY_DIR}"

if [[ -d "${MIXED_INPUT}" ]]; then
    INPUT_ONEWAY_DIR="$(cd "${MIXED_INPUT}" && pwd)"
    [[ -f "${INPUT_ONEWAY_DIR}/mixed_bundle/provenance_manifest.json" ]] || {
        echo "FAIL: mixed oneway outdir missing provenance manifest: ${INPUT_ONEWAY_DIR}" >&2
        exit 1
    }
    cp -R "${INPUT_ONEWAY_DIR}/." "${MIXED_ONEWAY_DIR}/"
else
    MIXED_MANIFEST="${MIXED_INPUT}"
    python3 "${ROOT_DIR}/scripts/validate_mixed_macro_local_generic_manifest.py" "${MIXED_MANIFEST}"
    bash "${ROOT_DIR}/tools/runners/mixed_bounded/run_mixed_macro_local_oneway_generic_v1.sh" "${MIXED_MANIFEST}" "${MIXED_ONEWAY_DIR}"
fi

python3 "${ROOT_DIR}/tools/exporters/mixed_bounded/export_mixed_local_feedback_reduced_generic.py" "${MIXED_ONEWAY_DIR}"

python3 - "${MBD_DECK}" "${REDUCED_DIR}/mbd_local_feedback_reduced.csv" "${MBD_REPLAY_DIR}/replay_from_mixed_feedback.dat" <<'PY'
from pathlib import Path
import sys


deck_path = Path(sys.argv[1]).resolve()
feedback_csv = Path(sys.argv[2]).resolve()
replay_deck = Path(sys.argv[3]).resolve()

deck_text = deck_path.read_text(encoding="utf-8")
for directive in ("MBD_LOCAL_FEEDBACK_MODE", "MBD_LOCAL_CONTACT_FILE"):
    for line in deck_text.splitlines():
        if line.strip().startswith(directive):
            raise SystemExit(f"FAIL: baseline MBD deck already contains {directive}: {deck_path}")

replay_text = (
    "# autogenerated mixed split replay handoff for MBD\n"
    "MBD_LOCAL_FEEDBACK_MODE LAGGED_REDUCED\n"
    f"MBD_LOCAL_CONTACT_FILE {feedback_csv}\n"
    f"{deck_text}"
)
replay_deck.write_text(replay_text, encoding="utf-8")
PY

"${ROOT_DIR}/bin/fem4c" \
    --mode=mbd \
    --mbd-integrator=explicit \
    --mbd-dt=1.0e-3 \
    --mbd-steps=5 \
    "${MBD_DECK}" \
    "${MBD_REPLAY_DIR}/baseline_generic.out" \
    >"${MBD_REPLAY_DIR}/baseline_generic.log" 2>&1

"${ROOT_DIR}/bin/fem4c" \
    --mode=mbd \
    --mbd-integrator=explicit \
    --mbd-dt=1.0e-3 \
    --mbd-steps=5 \
    "${MBD_REPLAY_DIR}/replay_from_mixed_feedback.dat" \
    "${MBD_REPLAY_DIR}/replay_generic.out" \
    >"${MBD_REPLAY_DIR}/replay_generic.log" 2>&1

python3 - "${FEM_DECK}" "${REDUCED_DIR}/fem_local_feedback_reduced.csv" "${FEM_REPLAY_DIR}/replay_from_mixed_feedback.dat" <<'PY'
from pathlib import Path
import shutil
import sys


deck_path = Path(sys.argv[1]).resolve()
feedback_csv = Path(sys.argv[2]).resolve()
replay_deck = Path(sys.argv[3]).resolve()
deck_dir = deck_path.parent
replay_dir = replay_deck.parent

deck_text = deck_path.read_text(encoding="utf-8")
for directive in ("FEM_LOCAL_FEEDBACK_MODE", "FEM_LOCAL_CONTACT_FILE"):
    for line in deck_text.splitlines():
        if line.strip().startswith(directive):
            raise SystemExit(f"FAIL: baseline FEM deck already contains {directive}: {deck_path}")

for raw_line in deck_text.splitlines():
    line = raw_line.strip()
    if not line or line.startswith("#"):
        continue
    fields = line.split()
    if fields[0] != "FEM_CONTACT_SURFACE_EDGE_SET" or len(fields) < 4:
        continue
    source_path = Path(fields[3])
    if source_path.is_absolute():
        continue
    resolved_source = (deck_dir / source_path).resolve()
    target_path = replay_dir / source_path.name
    if not resolved_source.is_file():
        raise SystemExit(f"FAIL: missing relative surface CSV referenced by deck: {resolved_source}")
    shutil.copyfile(resolved_source, target_path)

replay_text = (
    f"{deck_text.rstrip()}\n"
    "# autogenerated mixed split replay handoff for FEM\n"
    "FEM_LOCAL_FEEDBACK_MODE LAGGED_REDUCED\n"
    f"FEM_LOCAL_CONTACT_FILE {feedback_csv}\n"
)
replay_deck.write_text(replay_text, encoding="utf-8")
PY

"${ROOT_DIR}/bin/fem4c" \
    "${FEM_DECK}" \
    "${FEM_REPLAY_DIR}/baseline_generic.out" \
    >"${FEM_REPLAY_DIR}/baseline_generic.log" 2>&1

"${ROOT_DIR}/bin/fem4c" \
    "${FEM_REPLAY_DIR}/replay_from_mixed_feedback.dat" \
    "${FEM_REPLAY_DIR}/replay_generic.out" \
    >"${FEM_REPLAY_DIR}/replay_generic.log" 2>&1

python3 - "${OUT_DIR}" "${MIXED_ONEWAY_DIR}" "${MBD_REPLAY_DIR}" "${FEM_REPLAY_DIR}" "${HANDOFF_MANIFEST}" "${SUMMARY_JSON}" "${SUMMARY_MD}" <<'PY'
import csv
import json
import math
import sys
from pathlib import Path


def fail(message: str) -> None:
    raise SystemExit(f"FAIL: {message}")


def load_json(path: Path) -> dict:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        fail(f"missing JSON file: {path}")
    except json.JSONDecodeError as exc:
        fail(f"invalid JSON {path}: {exc}")
    if not isinstance(payload, dict):
        fail(f"{path} top-level JSON must be an object")
    return payload


def load_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    if not rows:
        fail(f"CSV has no rows: {path}")
    return rows


def ensure_finite(value: float, label: str) -> None:
    if not math.isfinite(value):
        fail(f"{label} must be finite")


out_dir = Path(sys.argv[1]).resolve()
mixed_oneway_dir = Path(sys.argv[2]).resolve()
mbd_replay_dir = Path(sys.argv[3]).resolve()
fem_replay_dir = Path(sys.argv[4]).resolve()
handoff_manifest_path = Path(sys.argv[5]).resolve()
summary_json_path = Path(sys.argv[6]).resolve()
summary_md_path = Path(sys.argv[7]).resolve()

mixed_feedback_manifest = load_json(mixed_oneway_dir / "reduced_feedback" / "mixed_feedback_reduced_manifest.json")
mixed_feedback_summary = load_json(mixed_oneway_dir / "reduced_feedback" / "mixed_feedback_reduced_summary.json")
mixed_oneway_summary = load_json(mixed_oneway_dir / "mixed_oneway_summary.json")
source_rows = mixed_feedback_manifest.get("rows")
if not isinstance(source_rows, list):
    fail("mixed feedback manifest rows must be an array")

mbd_baseline_trace = load_rows(mbd_replay_dir / "baseline_generic.out.contact_generic_trace.csv")
mbd_replay_trace = load_rows(mbd_replay_dir / "replay_generic.out.contact_generic_trace.csv")
mbd_replay_use = load_rows(mbd_replay_dir / "replay_generic.out.contact_generic_replay_use.csv")
fem_baseline_trace = load_rows(fem_replay_dir / "baseline_generic.out.fem_contact_generic_trace.csv")
fem_replay_trace = load_rows(fem_replay_dir / "replay_generic.out.fem_contact_generic_trace.csv")
fem_replay_use = load_rows(fem_replay_dir / "replay_generic.out.fem_contact_generic_replay_use.csv")

mbd_feedback_rows = load_rows(mixed_oneway_dir / "reduced_feedback" / "mbd_local_feedback_reduced.csv")
fem_feedback_rows = load_rows(mixed_oneway_dir / "reduced_feedback" / "fem_local_feedback_reduced.csv")

mbd_feedback_map = {(int(row["step"]), int(row["pair_id"])): row for row in mbd_feedback_rows}
fem_feedback_map = {(int(row["load_step"]), int(row["pair_id"])): row for row in fem_feedback_rows}
mbd_feedback_manifest_map = {}
fem_feedback_manifest_map = {}
for manifest_row in source_rows:
    if not isinstance(manifest_row, dict):
        fail("mixed feedback manifest row must be an object")
    engine = manifest_row.get("source_engine")
    feedback_row_key = manifest_row.get("feedback_row_key")
    if not isinstance(feedback_row_key, dict):
        fail("mixed feedback manifest row missing feedback_row_key")
    if engine == "MBD":
        key = (int(feedback_row_key["step"]), int(feedback_row_key["pair_id"]))
        mbd_feedback_manifest_map[key] = manifest_row
    elif engine == "FEM":
        key = (int(feedback_row_key["load_step"]), int(feedback_row_key["pair_id"]))
        fem_feedback_manifest_map[key] = manifest_row

mbd_external_rows = 0
mbd_fallback_rows = 0
mbd_changed_rows = 0
mbd_links = []
mbd_applied_feedback_keys = set()
mbd_baseline_map = {
    (int(row["step"]), int(row["pair_id"]), int(row["slave_vertex_id"])): row
    for row in mbd_baseline_trace
}
for row in mbd_replay_use:
    step = int(row["step"])
    pair_id = int(row["pair_id"])
    gamma_n_used = float(row["gamma_n_used"])
    k_pen_base = float(row["k_pen_base"])
    k_pen_used = float(row["k_pen_used"])
    ensure_finite(gamma_n_used, "mbd gamma_n_used")
    ensure_finite(k_pen_base, "mbd k_pen_base")
    ensure_finite(k_pen_used, "mbd k_pen_used")
    expected_key = (step - 1, pair_id)
    manifest_row = mbd_feedback_manifest_map.get(expected_key)
    feedback_row = mbd_feedback_map.get(expected_key)
    fallback_applied = row["feedback_source"] != "EXTERNAL"
    if row["feedback_source"] == "EXTERNAL":
        if feedback_row is None:
            fail(f"missing MBD reduced feedback row for replay step {step} pair_id={pair_id}")
        if abs(gamma_n_used - float(feedback_row["gamma_n"])) > 1.0e-12:
            fail(f"MBD replay gamma_n_used mismatch at step={step} pair_id={pair_id}")
        mbd_external_rows += 1
        mbd_applied_feedback_keys.add(expected_key)
    elif fallback_applied:
        mbd_fallback_rows += 1
    if fallback_applied:
        if abs(gamma_n_used - 1.0) > 1.0e-12:
            fail(f"MBD fallback gamma_n_used must be 1.0 at step={step} pair_id={pair_id}")
        if abs(k_pen_used - k_pen_base) > 1.0e-9:
            fail(f"MBD fallback k_pen_used must equal k_pen_base at step={step} pair_id={pair_id}")
    if manifest_row is not None:
        mbd_links.append(
            {
                "source_row_count": int(manifest_row.get("source_row_count", 0)),
                "valid_source_row_count": int(manifest_row.get("valid_source_row_count", 0)),
                "invalid_source_row_count": int(manifest_row.get("invalid_source_row_count", 0)),
                "reduced_feedback_csv_path": str(mixed_oneway_dir / "reduced_feedback" / "mbd_local_feedback_reduced.csv"),
                "reduced_feedback_row_key": {"step": expected_key[0], "pair_id": expected_key[1]},
                "replay_consume_artifact": str(mbd_replay_dir / "replay_generic.out.contact_generic_replay_use.csv"),
                "replay_consume_row_key": {"step": step, "pair_id": pair_id},
                "feedback_source": row["feedback_source"],
                "feedback_status": row["feedback_status"],
                "fallback_applied": fallback_applied,
            }
        )

for row in mbd_replay_trace:
    step = int(row["step"])
    pair_id = int(row["pair_id"])
    slave_vertex_id = int(row["slave_vertex_id"])
    if step <= 0:
        continue
    baseline_row = mbd_baseline_map.get((step, pair_id, slave_vertex_id))
    if baseline_row is None:
        fail(f"missing MBD baseline row for step={step} pair_id={pair_id} slave_vertex_id={slave_vertex_id}")
    fn_diff = abs(float(row["fn"]) - float(baseline_row["fn"]))
    penetration_diff = abs(float(row["penetration"]) - float(baseline_row["penetration"]))
    if fn_diff > 1.0e-9 or penetration_diff > 1.0e-12:
        mbd_changed_rows += 1

fem_external_rows = 0
fem_fallback_rows = 0
fem_changed_rows = 0
later_step_fem_replay_use_rows = 0
later_step_fem_fallback_rows = 0
later_step_fem_gamma_shift_rows = 0
later_step_fem_k_shift_rows = 0
later_step_fem_replay_trace_rows = 0
later_step_fem_changed_rows = 0
fem_links = []
fem_applied_feedback_keys = set()
fem_baseline_map = {
    (int(row["load_step"]), int(row["pair_id"]), int(row["slave_node_id"]), int(row["master_segment_id"])): row
    for row in fem_baseline_trace
}
for row in fem_replay_use:
    load_step = int(row["load_step"])
    pair_id = int(row["pair_id"])
    gamma_n_used = float(row["gamma_n_used"])
    k_pen_base = float(row["k_pen_base"])
    k_pen_used = float(row["k_pen_used"])
    ensure_finite(gamma_n_used, "fem gamma_n_used")
    ensure_finite(k_pen_base, "fem k_pen_base")
    ensure_finite(k_pen_used, "fem k_pen_used")
    expected_key = (load_step, pair_id)
    manifest_row = fem_feedback_manifest_map.get(expected_key)
    feedback_row = fem_feedback_map.get(expected_key)
    fallback_applied = row["feedback_source"] != "EXTERNAL"
    if load_step > 0:
        later_step_fem_replay_use_rows += 1
    if row["feedback_source"] == "EXTERNAL":
        if feedback_row is None:
            fail(f"missing FEM reduced feedback row for load_step={load_step} pair_id={pair_id}")
        if abs(gamma_n_used - float(feedback_row["gamma_n"])) > 1.0e-12:
            fail(f"FEM replay gamma_n_used mismatch at load_step={load_step} pair_id={pair_id}")
        fem_external_rows += 1
        fem_applied_feedback_keys.add(expected_key)
    elif fallback_applied:
        fem_fallback_rows += 1
    if fallback_applied:
        if abs(gamma_n_used - 1.0) > 1.0e-12:
            fail(f"FEM fallback gamma_n_used must be 1.0 at load_step={load_step} pair_id={pair_id}")
        if abs(k_pen_used - k_pen_base) > 1.0e-9:
            fail(f"FEM fallback k_pen_used must equal k_pen_base at load_step={load_step} pair_id={pair_id}")
        if load_step > 0:
            later_step_fem_fallback_rows += 1
    if load_step > 0:
        if abs(gamma_n_used - 1.0) > 1.0e-12:
            later_step_fem_gamma_shift_rows += 1
        if abs(k_pen_used - k_pen_base) > 1.0e-9:
            later_step_fem_k_shift_rows += 1
    if manifest_row is not None:
        fem_links.append(
            {
                "source_row_count": int(manifest_row.get("source_row_count", 0)),
                "valid_source_row_count": int(manifest_row.get("valid_source_row_count", 0)),
                "invalid_source_row_count": int(manifest_row.get("invalid_source_row_count", 0)),
                "reduced_feedback_csv_path": str(mixed_oneway_dir / "reduced_feedback" / "fem_local_feedback_reduced.csv"),
                "reduced_feedback_row_key": {"load_step": expected_key[0], "pair_id": expected_key[1]},
                "replay_consume_artifact": str(fem_replay_dir / "replay_generic.out.fem_contact_generic_replay_use.csv"),
                "replay_consume_row_key": {"load_step": load_step, "pair_id": pair_id},
                "feedback_source": row["feedback_source"],
                "feedback_status": row["feedback_status"],
                "fallback_applied": fallback_applied,
            }
        )

for row in fem_replay_trace:
    load_step = int(row["load_step"])
    key = (
        load_step,
        int(row["pair_id"]),
        int(row["slave_node_id"]),
        int(row["master_segment_id"]),
    )
    baseline_row = fem_baseline_map.get(key)
    if baseline_row is None:
        fail(f"missing FEM baseline row for {key!r}")
    fn_diff = abs(float(row["fn_n"]) - float(baseline_row["fn_n"]))
    penetration_diff = abs(float(row["penetration_m"]) - float(baseline_row["penetration_m"]))
    if load_step > 0:
        later_step_fem_replay_trace_rows += 1
    if fn_diff > 1.0e-9 or penetration_diff > 1.0e-12:
        fem_changed_rows += 1
        if load_step > 0:
            later_step_fem_changed_rows += 1

engine_histogram = mixed_feedback_summary.get("source_engine_histogram")
if not isinstance(engine_histogram, dict):
    fail("mixed feedback summary missing source_engine_histogram")
fem_load_steps = mixed_feedback_summary.get("fem_load_steps")
if not isinstance(fem_load_steps, list):
    fail("mixed feedback summary missing fem_load_steps")
mbd_source_rows = int(mixed_feedback_summary.get("mbd_source_rows", 0))
mbd_valid_source_rows = int(mixed_feedback_summary.get("mbd_valid_source_rows", 0))
mbd_invalid_source_rows = int(mixed_feedback_summary.get("mbd_invalid_source_rows", 0))
later_step_fem_feedback_rows = int(mixed_feedback_summary.get("later_step_fem_feedback_rows", 0))
later_step_fem_valid_source_rows = int(mixed_feedback_summary.get("later_step_fem_valid_source_rows", 0))
later_step_fem_invalid_source_rows = int(mixed_feedback_summary.get("later_step_fem_invalid_source_rows", 0))
feedback_available_flag = len(source_rows) > 0
skip_reason = "" if feedback_available_flag else "no_feedback_rows"
feedback_row_count = len(source_rows)
feedback_apply_count = mbd_external_rows + fem_external_rows
last_available_feedback_ref = None
last_applied_feedback_ref = None
for manifest_row in source_rows:
    if not isinstance(manifest_row, dict):
        fail("mixed feedback manifest row must be an object")
    engine = manifest_row.get("source_engine")
    feedback_row_key = manifest_row.get("feedback_row_key")
    feedback_csv = manifest_row.get("feedback_csv")
    exported_feedback = manifest_row.get("exported_feedback")
    if engine not in {"MBD", "FEM"}:
        fail("mixed feedback manifest row missing source_engine")
    if not isinstance(feedback_row_key, dict):
        fail("mixed feedback manifest row missing feedback_row_key")
    if not isinstance(feedback_csv, str) or not feedback_csv:
        fail("mixed feedback manifest row missing feedback_csv")
    if not isinstance(exported_feedback, dict):
        fail("mixed feedback manifest row missing exported_feedback")
    ref = {
        "source_engine": engine,
        "feedback_csv": feedback_csv,
        "feedback_row_key": feedback_row_key,
        "feedback_valid_flag": int(exported_feedback.get("valid_flag", 0)),
        "feedback_status": str(exported_feedback.get("status", "")),
    }
    last_available_feedback_ref = ref
    if engine == "MBD":
        feedback_key = (int(feedback_row_key["step"]), int(feedback_row_key["pair_id"]))
        if feedback_key in mbd_applied_feedback_keys:
            last_applied_feedback_ref = ref
    else:
        feedback_key = (int(feedback_row_key["load_step"]), int(feedback_row_key["pair_id"]))
        if feedback_key in fem_applied_feedback_keys:
            last_applied_feedback_ref = ref
last_available_differs_from_last_applied = (
    False
    if last_available_feedback_ref is None and last_applied_feedback_ref is None
    else last_available_feedback_ref != last_applied_feedback_ref
)
unapplied_terminal_candidate_flag = (
    False if last_available_feedback_ref is None else last_available_feedback_ref != last_applied_feedback_ref
)

handoff = {
    "contract_version": "mixed_macro_local_replay_split_generic_v1",
    "schema_name": "split_replay_handoff_manifest_v1",
    "mixed_source_job_id": mixed_feedback_manifest.get("source_oneway_summary", ""),
    "source_engine_histogram": engine_histogram,
    "mbd_source_rows": mbd_source_rows,
    "mbd_valid_source_rows": mbd_valid_source_rows,
    "mbd_invalid_source_rows": mbd_invalid_source_rows,
    "fem_distinct_load_step_count": int(mixed_feedback_summary.get("fem_distinct_load_step_count", 0)),
    "fem_load_steps": fem_load_steps,
    "later_step_fem_source_rows": int(mixed_feedback_summary.get("later_step_fem_source_rows", 0)),
    "later_step_fem_valid_source_rows": later_step_fem_valid_source_rows,
    "later_step_fem_invalid_source_rows": later_step_fem_invalid_source_rows,
    "later_step_fem_feedback_rows": later_step_fem_feedback_rows,
    "later_step_fem_fallback_rows": later_step_fem_fallback_rows,
    "later_step_fem_replay_use_rows": later_step_fem_replay_use_rows,
    "later_step_fem_replay_trace_rows": later_step_fem_replay_trace_rows,
    "later_step_fem_replay_changed_rows": later_step_fem_changed_rows,
    "joint_coupling": False,
    "mixed_replay": False,
    "mixed_solve": False,
    "live_cosim": False,
    "feedback_available_flag": feedback_available_flag,
    "skip_reason": skip_reason,
    "feedback_row_count": feedback_row_count,
    "feedback_apply_count": feedback_apply_count,
    "last_available_differs_from_last_applied": last_available_differs_from_last_applied,
    "unapplied_terminal_candidate_flag": unapplied_terminal_candidate_flag,
    "last_available_feedback_ref": last_available_feedback_ref,
    "last_applied_feedback_ref": last_applied_feedback_ref,
    "mbd_feedback_csv_path": str(mixed_oneway_dir / "reduced_feedback" / "mbd_local_feedback_reduced.csv"),
    "fem_feedback_csv_path": str(mixed_oneway_dir / "reduced_feedback" / "fem_local_feedback_reduced.csv"),
    "mbd_replay_outdir": str(mbd_replay_dir),
    "fem_replay_outdir": str(fem_replay_dir),
    "provenance_link": {
        "mixed_feedback_rows": source_rows,
        "mbd_replay_links": mbd_links,
        "fem_replay_links": fem_links,
    },
}
handoff_manifest_path.write_text(json.dumps(handoff, indent=2, sort_keys=True) + "\n", encoding="utf-8")

summary = {
    "route": "mixed_macro_local_replay_split_generic_v1",
    "pipeline_mode": "mixed_split_replay_consume_mvp",
    "mixed_replay": False,
    "mixed_solve": False,
    "live_cosim": False,
    "joint_coupling": False,
    "mbd_source_rows": mbd_source_rows,
    "mbd_valid_source_rows": mbd_valid_source_rows,
    "mbd_invalid_source_rows": mbd_invalid_source_rows,
    "mbd_feedback_rows": len(mbd_feedback_rows),
    "fem_feedback_rows": len(fem_feedback_rows),
    "mbd_replay_rows": len(mbd_replay_use),
    "fem_replay_rows": len(fem_replay_use),
    "mbd_external_rows": mbd_external_rows,
    "fem_external_rows": fem_external_rows,
    "mbd_fallback_rows": mbd_fallback_rows,
    "fem_fallback_rows": fem_fallback_rows,
    "mbd_replay_changed_rows": mbd_changed_rows,
    "fem_replay_changed_rows": fem_changed_rows,
    "fem_distinct_load_step_count": int(mixed_feedback_summary.get("fem_distinct_load_step_count", 0)),
    "fem_load_steps": fem_load_steps,
    "later_step_fem_source_rows": int(mixed_feedback_summary.get("later_step_fem_source_rows", 0)),
    "later_step_fem_valid_source_rows": later_step_fem_valid_source_rows,
    "later_step_fem_invalid_source_rows": later_step_fem_invalid_source_rows,
    "later_step_fem_feedback_rows": later_step_fem_feedback_rows,
    "later_step_fem_fallback_rows": later_step_fem_fallback_rows,
    "later_step_fem_replay_use_rows": later_step_fem_replay_use_rows,
    "later_step_fem_replay_trace_rows": later_step_fem_replay_trace_rows,
    "later_step_fem_replay_changed_rows": later_step_fem_changed_rows,
    "later_step_fem_gamma_shift_rows": later_step_fem_gamma_shift_rows,
    "later_step_fem_k_shift_rows": later_step_fem_k_shift_rows,
    "feedback_available_flag": feedback_available_flag,
    "skip_reason": skip_reason,
    "feedback_row_count": feedback_row_count,
    "feedback_apply_count": feedback_apply_count,
    "last_available_differs_from_last_applied": last_available_differs_from_last_applied,
    "unapplied_terminal_candidate_flag": unapplied_terminal_candidate_flag,
    "last_available_feedback_ref": last_available_feedback_ref,
    "last_applied_feedback_ref": last_applied_feedback_ref,
    "mbd_feedback_source": "EXTERNAL",
    "fem_feedback_source": "EXTERNAL",
    "mbd_replay_outdir": str(mbd_replay_dir),
    "fem_replay_outdir": str(fem_replay_dir),
    "split_replay_handoff_manifest": str(handoff_manifest_path),
    "overall_status": "PASS",
    "limitations": [
        "split replay consume MVP",
        "joint mixed replay not implemented",
        "mixed solve not implemented",
        "live co-sim not implemented",
        "not true lagged mixed co-sim",
        "not same-time mixed co-sim",
        "first-class feedback is gamma_n only",
        "local solver is proxy/MVP",
        "FEM source is static-only",
        "friction not implemented",
        "damping not implemented",
        "EHL out of scope",
        "monolithic out of scope",
    ],
}
summary_json_path.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8")

summary_md_lines = [
    "# mixed_macro_local_replay_split_generic_v1 summary",
    "",
    "- pipeline_mode: `mixed_split_replay_consume_mvp`",
    "- joint_coupling: `False`",
    "- mixed_replay: `False`",
    "- mixed_solve: `False`",
    "- live_cosim: `False`",
    f"- mbd_source_rows: `{summary['mbd_source_rows']}`",
    f"- mbd_valid_source_rows: `{summary['mbd_valid_source_rows']}`",
    f"- mbd_invalid_source_rows: `{summary['mbd_invalid_source_rows']}`",
    f"- mbd_feedback_rows: `{len(mbd_feedback_rows)}`",
    f"- fem_feedback_rows: `{len(fem_feedback_rows)}`",
    f"- mbd_replay_rows: `{len(mbd_replay_use)}`",
    f"- fem_replay_rows: `{len(fem_replay_use)}`",
    f"- mbd_external_rows: `{mbd_external_rows}`",
    f"- fem_external_rows: `{fem_external_rows}`",
    f"- mbd_fallback_rows: `{mbd_fallback_rows}`",
    f"- fem_fallback_rows: `{fem_fallback_rows}`",
    f"- mbd_replay_changed_rows: `{mbd_changed_rows}`",
    f"- fem_replay_changed_rows: `{fem_changed_rows}`",
    f"- fem_distinct_load_step_count: `{summary['fem_distinct_load_step_count']}`",
    f"- fem_load_steps: `{summary['fem_load_steps']}`",
    f"- later_step_fem_source_rows: `{summary['later_step_fem_source_rows']}`",
    f"- later_step_fem_valid_source_rows: `{summary['later_step_fem_valid_source_rows']}`",
    f"- later_step_fem_invalid_source_rows: `{summary['later_step_fem_invalid_source_rows']}`",
    f"- later_step_fem_feedback_rows: `{summary['later_step_fem_feedback_rows']}`",
    f"- later_step_fem_fallback_rows: `{summary['later_step_fem_fallback_rows']}`",
    f"- later_step_fem_replay_use_rows: `{summary['later_step_fem_replay_use_rows']}`",
    f"- later_step_fem_replay_trace_rows: `{summary['later_step_fem_replay_trace_rows']}`",
    f"- later_step_fem_replay_changed_rows: `{summary['later_step_fem_replay_changed_rows']}`",
    f"- later_step_fem_gamma_shift_rows: `{summary['later_step_fem_gamma_shift_rows']}`",
    f"- later_step_fem_k_shift_rows: `{summary['later_step_fem_k_shift_rows']}`",
    f"- feedback_available_flag: `{summary['feedback_available_flag']}`",
    f"- skip_reason: `{summary['skip_reason']}`",
    f"- feedback_row_count: `{summary['feedback_row_count']}`",
    f"- feedback_apply_count: `{summary['feedback_apply_count']}`",
    f"- last_available_differs_from_last_applied: `{summary['last_available_differs_from_last_applied']}`",
    f"- unapplied_terminal_candidate_flag: `{summary['unapplied_terminal_candidate_flag']}`",
    "",
    "## truth",
    "",
    "- split replay consume MVP only.",
    "- joint mixed replay ではない.",
    "- mixed solve ではない.",
    "- live co-sim ではない.",
    "- true lagged mixed co-sim ではない.",
    "- same-time mixed co-sim ではない.",
    "- first-class feedback は gamma_n のみ.",
    "- local solver は proxy / MVP.",
    "- FEM source は static-only.",
    "- source_step / apply_step / dt_comm / dt_sub / subcycle_count は time-coupled route ではなく reduced-key bounded route なので top-level summary には持たない.",
]
summary_md_path.write_text("\n".join(summary_md_lines) + "\n", encoding="utf-8")

print(
    "PASS mixed_macro_local_replay_split_generic_v1 "
    f"mbd_replay_rows={len(mbd_replay_use)} fem_replay_rows={len(fem_replay_use)} "
    f"mbd_changed_rows={mbd_changed_rows} fem_changed_rows={fem_changed_rows}"
)
PY

echo "PASS: run_mixed_macro_local_replay_split_generic_v1 out_dir=${OUT_DIR}"
