name: chrono-2d-ci-experimental

on:
  workflow_dispatch:
    inputs:
      run_bench:
        description: "Run bench (make bench) and compare drift"
        required: false
        default: "false"
      fail_on_drift:
        description: "Fail when bench drift exceeds threshold"
        required: false
        default: "false"

permissions:
  contents: read
  actions: read
  id-token: write

  env:
    CSV_PATH: artifacts/kkt_descriptor_actions_local.csv
    BENCH_CSV: bench_pivots.csv
    BENCH_DRIFT_THRESHOLD: "1.5"  # 1.5x drift triggers warning
    BUILD_TIMEOUT: 20m
    TEST_TIMEOUT: 10m
    REPORT_PATH: artifacts_ci_report.md
    SUMMARY_PATH: artifacts_ci_summary.md
    ENV_PATH: artifacts_env.txt
    LOG_TAIL: test.log.tail

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install deps (OpenMP only)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3 python3-pip
          gcc --version
          python3 --version

      - name: Build chrono-2d tests
        timeout-minutes: 20
        run: |
          make clean
          make tests

      - name: Run chrono-2d tests (with retry=1)
        id: run_tests
        continue-on-error: true
        timeout-minutes: 10
        run: |
          rm -f test.log
          set -o pipefail
          attempt() {
            if make test > test.log 2>&1; then
              tail -n 200 test.log
              echo "status=success" >> $GITHUB_OUTPUT
              return 0
            else
              tail -n 400 test.log
              return 1
            fi
          }
          if attempt; then
            exit 0
          else
            echo "retry=1" >> $GITHUB_OUTPUT
            sleep 5
            if attempt; then
              echo "status=flaky-pass" >> $GITHUB_OUTPUT
              exit 0
            else
              echo "status=failure" >> $GITHUB_OUTPUT
              exit 1
            fi
          fi

      - name: CSV schema check (extended)
        run: |
          python3 tools/check_chrono2d_csv_schema.py "${CSV_PATH}"

      - name: Record environment
        if: always()
        run: |
          {
            echo "# Environment"
            echo "Run: ${GITHUB_RUN_ID}"
            echo "OS: $(uname -a)"
            echo "gcc: $(gcc --version | head -n 1)"
            echo "python: $(python3 --version)"
            echo "date: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
          } > "${ENV_PATH}"

      - name: Prepare readable logs
        if: always()
        run: |
          tail -n 200 test.log > "${LOG_TAIL}" || true

      - name: Generate CI report
        if: always()
        run: |
          python3 tools/generate_chrono2d_ci_report.py \
            --run-id "${GITHUB_RUN_ID}" \
            --csv "${CSV_PATH}" \
            --log "${LOG_TAIL}" \
            --env "${ENV_PATH}" \
            --out "${REPORT_PATH}"

      - name: Summarize Run ID and artifacts
        if: always()
        run: |
          {
            echo "- Run: #${GITHUB_RUN_ID} (chrono-2d experimental)"
            echo "- Artifact: chrono-2d-ci-exp-${GITHUB_RUN_ID}"
            echo "- CSV: ${CSV_PATH} (schema: time,case,method,vn,vt,mu_s,mu_d,stick,condition_bound,condition_spectral,min_pivot,max_pivot)"
            echo "- Logs: test.log (tail uploaded), env: ${ENV_PATH}, report: ${REPORT_PATH}"
            echo "- Status: ${{ steps.run_tests.outputs.status }}"
            echo "- Retry: ${{ steps.run_tests.outputs.retry || '0' }}"
          } > "${SUMMARY_PATH}"

      - name: Upload minimal artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: chrono-2d-ci-exp-${{ github.run_id }}
          path: |
            test.log
            ${LOG_TAIL}
            ${CSV_PATH}
            ${SUMMARY_PATH}
            ${ENV_PATH}
            ${REPORT_PATH}
          retention-days: 30

      - name: Fail if tests failed
        if: steps.run_tests.outcome == 'failure'
        run: exit 1

  bench-optional:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: |
      github.event.inputs.run_bench == 'true'
      && !contains(github.event.head_commit.message, '[skip-ci]')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install deps (OpenMP only)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3 python3-pip
          gcc --version
          python3 --version

      - name: Run bench (opt-in)
        id: bench_run
        continue-on-error: true
        run: |
          make bench > bench.log 2>&1 || true
          if test -f "${BENCH_CSV}"; then
            tail -n 20 "${BENCH_CSV}"
          fi

      - name: Bench drift check (1.5x warn)
        if: always()
        run: |
          OPT_FAIL=""
          if [ "${{ github.event.inputs.fail_on_drift }}" = "true" ]; then
            OPT_FAIL="--fail-on-drift"
          fi
          python3 tools/compare_bench_csv.py "${BENCH_CSV}" --threshold ${BENCH_DRIFT_THRESHOLD} ${OPT_FAIL} > bench_drift.txt || true

      - name: Upload bench artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: chrono-2d-bench-exp-${{ github.run_id }}
          path: |
            bench.log
            ${BENCH_CSV}
            bench_drift.txt
          retention-days: 14
