name: Nightly Coupled & Island Regression

on:
  schedule:
    - cron: '30 2 * * *'
  workflow_dispatch:

jobs:
  nightly-regression:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential python3

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pyyaml

      - name: Build coupled/island regression tests
        working-directory: chrono-C-all
        run: |
          make clean
          make \
            tests/test_coupled_constraint \
            tests/test_coupled_constraint_endurance \
            tests/test_island_contact_constraint \
            tests/test_island_parallel_contacts \
            tests/test_island_polygon_longrun

      - name: Run coupled benchmark
        run: |
          mkdir -p artifacts/nightly
          python3 tools/run_coupled_benchmark.py \
            --config config/coupled_benchmark_thresholds.yaml \
            --csv-validation warn \
            --csv-validation-jsonl artifacts/nightly/benchmark_validation.jsonl \
            --output data/coupled_benchmark_metrics.csv

      - name: Generate condition gap report
        run: |
          python3 tools/report_coupled_condition_gap.py \
            --input data/coupled_benchmark_metrics.csv \
            --output artifacts/nightly/condition_gap.md

      - name: Generate diagnostic markdown
        run: |
          mkdir -p artifacts/nightly
          python3 tools/diagnostic_log_report.py \
            data/coupled_constraint_endurance.csv \
            --output artifacts/nightly/diagnostics.md \
            --anomaly-jsonl artifacts/nightly/benchmark_validation.jsonl \
            | tee artifacts/nightly/diagnostics_console.log

      - name: Compare against chrono-main baseline
        env:
          CHRONO_BASELINE_CSV: ${{ env.CHRONO_BASELINE_CSV }}
        run: |
          mkdir -p artifacts/nightly
          BASELINE_PATH="${CHRONO_BASELINE_CSV:-third_party/chrono/chrono-main/data/coupled_benchmark_metrics.csv}"
          if [ -f "$BASELINE_PATH" ]; then
            python3 tools/compare_benchmark_results.py \
              --baseline "$BASELINE_PATH" \
              --current data/coupled_benchmark_metrics.csv \
              --output artifacts/nightly/benchmark_diff.md \
              --csv-output artifacts/nightly/benchmark_diff.csv
          else
            echo "Baseline CSV not found at $BASELINE_PATH; skipping comparison."
          fi

      - name: Validate endurance summary schema
        run: |
          mkdir -p artifacts/nightly
          SUMMARY=data/endurance_archive/latest.summary.json
          if [ -f "$SUMMARY" ]; then
            python3 tools/validate_latest_summary_schema.py \
              --summary-json "$SUMMARY" \
              --output-markdown artifacts/nightly/latest_summary_validation.md \
              --output-json artifacts/nightly/latest_summary_validation.json \
              --fail-on-error
          else
            echo "latest.summary.json not found at $SUMMARY; skipping validation." \
              | tee artifacts/nightly/latest_summary_validation.md
            cat <<'EOF' > artifacts/nightly/latest_summary_validation.json
{
  "status": "SKIPPED",
  "message": "latest.summary.json not available on nightly runner"
}
EOF
          fi

      - name: Run nightly regression suite
        run: |
          python3 tools/run_nightly_regressions.py \
            --log-dir artifacts/nightly/logs \
            --output-csv artifacts/nightly/regression_results.csv \
            --timeout 900 \
            --diff-summary artifacts/nightly/mode_mismatch_summary.csv

      - name: Lint nightly regression CSV
        run: |
          python3 tools/lint_nightly_results.py \
            artifacts/nightly/regression_results.csv \
            --summary artifacts/nightly/mode_mismatch_summary.csv \
            --fix | tee artifacts/nightly/lint_report.txt

      - name: Lint endurance plan
        run: |
          mkdir -p artifacts/nightly
          PLAN=data/endurance_archive/plan.csv
          REPORT=artifacts/nightly/endurance_plan_lint.txt
          JSON=artifacts/nightly/endurance_plan_lint.json
          if [ -f "$PLAN" ]; then
            set -o pipefail
            if python3 tools/lint_endurance_plan.py \
              "$PLAN" \
              --max-delete 10 \
              --max-delete-max-age 6 \
              --max-delete-max-entries 6 \
              --fail-on-duplicates \
              | tee "$REPORT"; then
              STATUS="PASS"
            else
              STATUS="FAIL"
            fi
            cat <<EOF > "$JSON"
{
  "status": "$STATUS",
  "plan": "$PLAN"
}
EOF
          else
            echo "Plan CSV not found at $PLAN; skipping lint." | tee "$REPORT"
            cat <<'EOF' > "$JSON"
{
  "status": "SKIPPED",
  "message": "Plan CSV not available on nightly runner"
}
EOF
          fi

      - name: Upload regression artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coupled-island-nightly
          path: |
            artifacts/nightly/regression_results.csv
            artifacts/nightly/logs
            artifacts/nightly/mode_mismatch_summary.csv
            artifacts/nightly/lint_report.txt
            artifacts/nightly/benchmark_validation.jsonl
            artifacts/nightly/condition_gap.md
            artifacts/nightly/diagnostics.md
            artifacts/nightly/diagnostics_console.log
            artifacts/nightly/benchmark_diff.md
            artifacts/nightly/benchmark_diff.csv
            artifacts/nightly/endurance_plan_lint.txt
            artifacts/nightly/endurance_plan_lint.json
            artifacts/nightly/latest_summary_validation.md
            artifacts/nightly/latest_summary_validation.json
